# Generated by Django 5.2.3 on 2025-06-24 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="writer",
            field=models.CharField(default="익명", max_length=30),
            preserve_default=False,
        ),
    ]
